config/routes.rb
Rails.application.routes.draw do
	devise_for :users   ##2  ????????????*** /users 
	resources :messages do ### ???????????  /messages  # messages ile ilişkili messages_controller.rb
		resources :comments #2#???????  //messages/comments # controller ile ilişkili comments_controller.rb
	end #2# ????????????????
	root 'messages#index' ### ana index messages /messages = index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to:user ##2# bir mesajların sahibi tek bir kullanıcıdır
	has_many :comments #2# 1 mesajın birçok yorumu olabilir
end

app/models/user.rb
class User < ApplicationRecord
 has_many :messages##2# bir kullanıcının büssürü mesajı olabilir
 has_many :comments ##2## bir kullanıcının birçok yorumu olabilir
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message ## işlem yapılcak olan mesaj bulma methodu before ise yapılacak ilk işlem bu sayfa açılışında
	before_action :find_comment, only: [:edit, :update, :destroy] ## sonra bu method edit update only meyhodları için çalıştırılıyor  
### hepsi 2
	def create 
		##@message = Message.find(params[:message_id]) #2# mesaj idsini bularak ve o satırdaki tüm bilgileri getiriyor ,  Message modelle , veritababana bağlanarak messages tablosundan 
		@comment = @message.comments.create(comment_params) #2#
		@comment.user_id = current_user.id  #2#
		
		if @comment.save
			redirect_to message_path(@message) ## yorum kaydedilince yorum yapılan mesaj idisine yönlendirme yapılıyor
		else
		 render 'new' ## kaydedilmezse
		end
	end
	
	def edit
		##@message = Message.find(params[:message_id]) ##
		##@comment = @message.comments.find(params[:id]) # burada join yapılmış gibi
	end	
		
	def update
		if @comment.update(comment_params) ##
		redirect_to message_path(@message) ##işlem yapıldıktan sonra @message de id'si ile,  message sayfasına döner
		else
			render 'edit' ##
		end
	end
	
	def destroy
		@comment.destroy##
		redirect_to message_path(@message)#
		end
	private 
	
		def comment_params
			params.require(:comment).permit(:content) ## update ve create işlemlerinde kullandık
		end
		
		def find_message
			@message = Message.find(params[:message_id]) ##mesaj idsini bularak ve o satırdaki tüm bilgileri getiriyor ,  Message modelle , veritababana bağlanarak messages tablosa erişerek yapıyor
		end
		
		def find_comment
			@comment = @message.comments.find(params[:id]) 
			##bunlar join gibi düşünülebir  @message deki mesaj idsi ne bağlı comments tablosundan  belirtilen  id dek satırdaki tüm bilgler getiriliyor
		end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy] # show edit update destroy methodlarında find_message methodu geçrli olacak
	before_action :authenticate_user!, except: [:index, :show]##
	def index ###
		@messages = Message.all.order("created_at DESC")##SQL DE SELECT "messages".* FROM "messages" ORDER BY created at DESC
	end
	
	def new ##
		@message = current_user.messages.build#2# #1#Message.new ##
	end
	
	def show ##
		#ilk kullanım şekli##@message = Message.find(params[:id]) ## databaseden params içinden  o id bulunup getiriliyor sonra @ message html kısmında işlenir 
		# şimdi ikinci kullanım şeklini kullanıyoruz  ## def _find method ve before action methodlarıyla
	end
	
	def create ##
		# title: params[:title], description: [:description]
		##@message.save  diğer kullanım şekli
		@message =current_user.messages.build(message_params)  ##Message.new(message_params) ##
		if @message.save  ##mesaj kayıt true döndürürse
			redirect_to root_path ##ana sayfaya yönlendirir
		else
			render 'new' ##
		end ##
		
	end ##
	
	def edit
	
	end
	
	def update
		if @message.update(message_params)  ## mesaj bulunduysa ve update edildiyse
			redirect_to message_path ## http://localhost:3000/messages/3 yani showa yönlendrilir gider
		else
			render 'edit'  ## true değer dönmezse edite gelir tekrar  http://localhost:3000/messages/3/edit
		end
	
	end
	
	def destroy
		@message.destroy
		redirect_to root_path ## mesaj silinince indexe  http://localhost:3000/messages yönelir
	
	end
	
	private ##
	
		def message_params ##
			params.require(:message).permit(:title, :description) #########################
		end  ##
		
		def find_message
			@message = Message.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment"><!--##5 -->	
	<!--comment için ###2 -->
	<p class ="comment-content"><%= comment.content %></p> <!--###2 --><!--##5 -->
	<p class ="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago </p><!--###2 --> <!--##5 -->

	<div class = "links" <!--##5 -->
		<% if user_signed_in? %> <!--##2 -->
			<% if comment.user_id == current_user.id %> <!--###2 -->
				<%= link_to "Edit",edit_message_comment_path(comment.message, comment) %> <!--###2 -->
				<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure ?"} %> <!--###2 -->
			<%end%>
		<%end%>
	</div>
</div>

app/views/comments/_form.html.erb
<!--###comment için form oluşturduk  -->
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "Yorum Yap" %>
	<%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<!--############################-->
<h1>Yorumu Düzenle</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
	<%= f.input :content, label: "Yorum" %>
	<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MesajKutusu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
	<div class="navbar navbar-dafault">  <!--  ##2 bootstrap -->
		<div class ="container">	<!--  ##2 gem bootstrap -->
			<div class="navbar-header"> 	<!--  ##2 gem bootstrap -->
				<%= link_to "Mesaj Kutusu", root_path, class:"navbar-brand" %>  <!--  ##2 gem bootstrap -->
				<!--http://localhost:3000/messages -->
			</div>        <!--  ##2 gem bootstrap -->
			<ul class="nav navbar-nav">
				<% unless user_signed_in? %> 
				<li><%= link_to "Üye Ol",new_user_registration_path %></li>
				<!--http://localhost:3000/users/sign_up -->
				<% end %> 
				<% if user_signed_in? %><!-- kullanıcı giriş yaptıysa -->
					<li><%= link_to "Oturumu Kapat",destroy_user_session_path, method: :delete %></li>
					<!-- http://localhost:3000/users/sign_out -->
					<!-- destroy verblerde method: :delete kullanılır -->
				<% else %>
					<li> <%= link_to "Giriş Yap",new_user_session_path %></li>
					<!-- http://localhost:3000/users/sign_in  -->
				
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<p><%= link_to "Yeni Mesaj Ekle", new_message_path, class: "navbar-right navbar-text navbar-link" %></p>
				<!-- http://localhost:3000/messages/new-->
			<%end %>
		</div>  <!--  ##2 gem bootstrap -->
	</div> <!--  ##2 gem bootstrap -->

  
       <p class="notice"><%= notice %></p> <!-- gem devise -->
       <p class="alert"><%= alert %></p>   <!-- gem devise -->
	   
   <div class ="container">   <!--  ##5  -->
      <%= yield %>  <!--  ##5  -->
  </div>
  
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Mesaj Başlığı" %>
	<%= f.input :description, label: "Açıklama" %>
	<%= f.button :submit%>
<% end %>

app/views/messages/edit.html.erb
<h1> Mesajı Düzenle </h1>
<!-- http://localhost:3000/messages/4/edit  -->
<%= render 'form' %>

app/views/messages/index.html.erb
<!-- http://localhost:3000/messages/ -->


<% @messages.each do |message| %>   <!-- controller index methodundan @messages verileri veri tabanından  iterate çekiliyor -->
	<div class = "col-md-4"> <!-- ##5 -->
		<div class ="message"> <!-- ##5 -->
			<h2 class= message-title> <%= message.title %> </h2> <!-- ##5 -->
			<%= link_to "mesajı göster",message_path(message), class: "btn-custom" %>  <!##5 --"btn btn-default" -->
			
			<!-- message_path(message) show methodun,  bootstrap tarafı class: "btn btn-default",http://localhost:3000/messages/5   -->
		</div>
	</div>
<% end %>


<% if user_signed_in? %>
	<%= link_to "Yeni Mesaj", new_message_path %>
	<!--http://localhost:3000/messages/new-->
<% end %>

<!--HTML  DÜZENİNDE DEĞİLSE O KOD BOOTSTRAPANDR -->

app/views/messages/new.html.erb
<div class "col-md-8 col-md-offset-2"> 	<!-- ##5-->
	<!--http://localhost:3000/messages/new -->
	<h1>Yeni Mesaj </h1> <!-- -->

	<%= render 'form' %>
	
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2" > <!-- ##5 -->
	<div class = "message-show"> <!-- ##5 -->
		<!--http://localhost:3000/messages/3-->
		<h2><%= @message.title %></h2>  
		<p class= "message-posted-by">Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago </p> <!-- ##5 -->
		<p class= "message-desc"><%= @message.description %></p> <!-- ##5 -->

		<h3>Yorumlar:</h3>     <!--önceden yapılan yorumları gösterir -->
		<%= render @message.comments %> 


		<h3 class = "reply-to-msg">Yorum Yap:</h3> <!-- ##5 -->
		<%= render 'comments/form' %>

		<div class= "links btn-group"> <!-- ##5 -->
			<%= link_to "Geri Dön", root_path, class:"btn btn-default"%>   <!-- ##5 -->
			<% if user_signed_in? %>
				<% if @message.user_id == current_user.id %>
					<!--http://localhost:3000/ indexe yönenir -->
					<%= link_to "Düzenle", edit_message_path(@message), class:"btn btn-default" %>  <!-- ##5 --> 
					<!-- buraya yönlenir http://localhost:3000/messages/3/edit -->
					<%= link_to "Mesajı Sil", message_path(@message), method: :delete, data: {confirm: "Are you sure"}, class:"btn btn-default" %> <!-- ##5 -->
					<!--http://localhost:3000/ indexe yönenir bu kısım pop-up onay data: {confirm: "Are you sure"}-->
				<%end%>
			<% end %>
		</div>
	</div>
</div>